# Generated by Django 5.0 on 2023-12-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='copyrights',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
